version: '3.8'

services:
  # Server (Backend API)
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    container_name: mentorlabs-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-ff0bf2616b1454e99af428823b442b95db237ca60fbde63ab7b51e5d97dd4d50}
    ports:
      - "3000:3000"
    networks:
      - mentorlabs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web (Frontend)
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: mentorlabs-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WEB_URL=${NEXT_PUBLIC_WEB_URL}
    ports:
      - "3001:3000"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - mentorlabs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mentorlabs-network:
    driver: bridge
    external: false